### ISSUE TITLE
Exemplo W nao esta funcionando

### ISSUE THREAD

**Issue by emanuelespies** [careertopologies/concepts-and-examples#1]
Ola,

Achei a iniciativa super interessante e estou curiosa pelos proximos passos.

So queria avisar que o link para o exemplo W vai para um 404: https://github.com/careertopologies/concepts-and-examples/blob/main/career-w.png

E no readme tem o Y duas vezes.

Att,

**Comment by guiofsaints** [comment]
Valeu @emanuelespies , vou corrigir!
