### ISSUE TITLE
Erro de digitação

### ISSUE THREAD

**Issue by lutchenca** [careertopologies/concepts-and-examples#2]
![Preview](https://user-images.githubusercontent.com/36814440/172660577-2a0068b2-c81a-4b56-897a-64f385aac5a6.png)
Substituir "na carteira" por "na carreira".

**Comment by guiofsaints** [comment]
Obrigado pelo feedback @lutchenca, na verdade, está correto "carteira" seria na CLT o equivalente ao que os recrutadores registram. 

Mas seu feedback mostrou que dá para deixar mais claro, vou ajustar e depois subir mais descrições no README.

Muito obrigado!
